# Generated by Django 3.2.8 on 2021-10-27 16:45

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(blank=True, to='core.OrderItem')),
                ('vendor',models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, to='core.vendor')),
                ('comment',models.TextField(blank=True, max_length=500, null=True)),
                ('placed_by',models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('placed_date',models.DateTimeField(auto_now_add=True, null=True)),
                ('delivery_date',models.DateField(blank=True, null=True)),
                ('notification_sent',models.BooleanField(default=False)),

            ],
        ),
    ]
